name: Build Solstice Project

on:
  push:
    branches:
      - main # 监听main分支的推送事件
  pull_request: # 监听拉取请求事件

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSVC
        uses: microsoft/setup-msvc@v1
        with:
          vs-version: 2022
          architecture: x64
          include-preview: true

      - name: Configure CMake
        run: cmake -S. -B build -DCMAKE_BUILD_TYPE=Release
        env:
          
          PATH: ${{ env.PATH }};C:/msys64/mingw64/bin

      - name: Build project
        run: cmake --build build --config Release
