name: Solstice Build

##By SnowLotus

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Debug or Release)'
        required: true
        default: 'Debug'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: cmake-actions/configure@v1
        with:
          cmake-version: '3.28'
          build-type: ${{ github.event.inputs.build_type }}

      - name: Build project
        uses: cmake-actions/build@v1
